const actionTypes = {
  FETCH_REQUEST_STATUSES_OPTIONS: 'FETCH_REQUEST_STATUSES_OPTIONS'
}

const mutationTypes = {
  SET_REQUEST_STATUSES_OPTIONS: 'SET_REQUEST_STATUSES_OPTIONS',
  SET_GLOBAL_SEARCH_FILTERS: 'SET_GLOBAL_SEARCH_FILTERS',
  SET_GLOBAL_SEARCH_FILTERS_SETTINGS: 'SET_GLOBAL_SEARCH_FILTERS_SETTINGS',
  SET_GLOBAL_SEARCH_ADDRESS_FILTERS_SETTINGS:
    'SET_GLOBAL_SEARCH_ADDRESS_FILTERS_SETTINGS'
}

const getterTypes = {
  GET_REQUEST_STATUSES_OPTIONS_CONSTANTS:
    'GET_REQUEST_STATUSES_OPTIONS_CONSTANTS'
}

export { actionTypes, mutationTypes, getterTypes }
