const actionTypes = {
  FETCH_REQUEST_STATUSES_OPTIONS: 'FETCH_REQUEST_STATUSES_OPTIONS'
}

const mutationTypes = {
  SET_REQUEST_STATUSES_OPTIONS: 'SET_REQUEST_STATUSES_OPTIONS'
}

const getterTypes = {
  GET_REQUEST_STATUSES_OPTIONS_CONSTANTS:
    'GET_REQUEST_STATUSES_OPTIONS_CONSTANTS'
}

export { actionTypes, mutationTypes, getterTypes }
