const actionTypes = {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_REQUEST_LIST: 'FETCH_REQUEST_LIST',
  SAVE_REQUEST: 'SAVE_REQUEST',
  CHANGE_REQUEST_STATUS: 'CHANGE_REQUEST_STATUS',
  FETCH_REQUEST_STATUSES: 'FETCH_REQUEST_STATUSES',
  RESET_REQUEST: 'RESET_REQUEST'
}

const mutationTypes = {
  SET_REQUEST: 'SET_REQUEST',
  RESET_REQUEST: 'RESET_REQUEST',
  RESET_REQUEST_LIST: 'RESET_REQUEST_LIST',
  SET_REQUEST_STATUSES: 'SET_REQUEST_STATUSES',
  SET_PROP: 'SET_PROP'
}

const getterTypes = {
  GET_REQUEST: 'GET_REQUEST'
}

export { actionTypes, mutationTypes, getterTypes }
