---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 8
    - role: ansible-role-weblogic
      wls_version: "12.2.1.3.0"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/app-servers/weblogic/12.2.1.3.0/V886423-01.zip"
