---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 6
      java_minor_version: 45
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-6u45-linux-x64.tar.gz"
    - role: ansible-role-weblogic
      wls_version: "10.3.6.0"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-commerce-suite/app-servers/weblogic/10.3.6.0/V29856-01.zip"
      swapfile_path: "/swapfile-{{ wls_version }}-{{ ansible_distribution_version }}"
