---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 7
      java_minor_version: 191
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-7u191-linux-x64.tar.gz"
    - role: ansible-role-weblogic
      wls_version: "12.1.2.0.0"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-commerce-suite/app-servers/weblogic/12.1.2.0.0/V38518-01.zip"
      swapfile_path: "/swapfile-{{ wls_version }}-{{ ansible_distribution_version }}"
